name = "Pigman Marketplace"
description = "Adds a marketplace for you to trade for materials"
author = "Teh Scot"
version = "0.1"
forumthread = "N/A"
api_version = 6
icon_atlas = "iconImage.xml"
icon = "iconImage.tex"
dont_starve_compatible = true
reign_of_giants_compatible = true

configuration_options =
{
	{
		name = "recipeDifficulty",
        label = "Recipe Difficulty",
        options = 
        {
            {description = "Cheaty", data = "diffCheaty"}, 
            {description = "Easy", data = "diffEasy"},
			{description = "Medium", data = "diffMedium"},
			{description = "Hard", data = "diffHard"},
        }, 
        default = "diffMedium",
    },
	{
		name = "sellValue",
        label = "Selling Value",
        options = 
        {
            {description = "100% of Buying", data = "1"}, 
            {description = "75% of Buying", data = "0.75"},
			{description = "50% of Buying", data = "0.5"},
			{description = "25% of Buying", data = "0.25"},
			{description = "Disable Selling", data = "0"},
        }, 
        default = "0.5",
    },
	{
		name = "pigHouse",
        label = "Required Pig Houses",
        options = 
        {
            {description = "None Required", data = "0"}, 
			{description = "2", data = "2"}, 
			{description = "4", data = "4"}, 
			{description = "6", data = "6"}, 
			{description = "8", data = "8"}, 
			{description = "10", data = "10"}, 
            
        }, 
        default = "6",
    },
	{
		name = "dug_grass",
        label = "Grass Tuft Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor1",
    },
	{
		name = "cutgrass",
        label = "Cut Grass Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor40",
    },
	{
		name = "rocks",
        label = "Rocks Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor40",
    },
	{
		name = "dug_sapling",
        label = "Sapling Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor1",
    },
	{
		name = "log",
        label = "Log Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor40",
    },
	
	--New config values
	
		{
		name = "beardhair",
        label = "Beard Hair Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "5Gfor1",
    },
			{
		name = "bluegem",
        label = "Blue Gem Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "10Gfor1",
    },
		{
		name = "pinecone",
        label = "Pine Cone Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor10",
    },
	{
		name = "charcoal",
        label = "Charcoal Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor10",
    },
	{
		name = "cutreeds",
        label = "Cut Reeds Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor5",
    },
		{
		name = "deerclops_eyeball",
        label = "Deerclops Eyeball Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "200Gfor1",
    },
	
		{
		name = "feather_crow",
        label = "Jet Feather Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor1",
    },
		{
		name = "feather_robin",
        label = "Crimson Feather Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor5",
    },
	
		{
		name = "feather_robin_winter",
        label = "Azure Feather Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor1",
    },
	
		{
		name = "fireflies",
        label = "Fireflies Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "5Gfor1",
    },
	
		{
		name = "flint",
        label = "Flint Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor20",
    },
			
	{
		name = "gear",
        label = "Gears Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "10Gfor1",
    },
	{
		name = "greengem",
        label = "Green Gem Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "50Gfor1",
    },
	
	{
		name = "honeycomb",
        label = "Honeycomb Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "20Gfor1",
    },
	
	{
		name = "horn",
        label = "Beefalo Horn Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "10Gfor1",
    },
	
		{
		name = "houndstooth",
        label = "Hounds Tooth Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "5Gfor1",
    },
	
		{
		name = "lightbulb",
        label = "Light Bulb Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor1",
    },
	
		{
		name = "livinglog",
        label = "Living Log Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "5Gfor1",
    },
	
		{
		name = "mandrake",
        label = "Mandrake Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "100Gfor1",
    },
	{
		name = "manrabbit_tail",
        label = "Bunny Puff Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "5Gfor1",
    },
	{
		name = "marble",
        label = "Marble Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "3Gfor1",
    },
	{
		name = "minotaurhorn",
        label = "Guardian Horn Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "200Gfor1",
    },
	{
		name = "nightmarefuel",
        label = "Nightmare Fuel Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "10Gfor1",
    },	
	{
		name = "nitre",
        label = "Nitre Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor20",
    },
	{
		name = "orangegem",
        label = "Orange Gem Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "50Gfor1",
    },	
	{
		name = "marble",
        label = "Marble Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "3Gfor1",
    },
	{
		name = "pigskin",
        label = "Pig Skin Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "5Gfor1",
    },
	{
		name = "poop",
        label = "Manure Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor1",
    },
	{
		name = "purplegem",
        label = "Purple Gem Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "20Gfor1",
    },
	{
		name = "redgem",
        label = "Red Gem Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "10Gfor1",
    },
	{
		name = "silk",
        label = "Silk Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "3Gfor1",
    },
	{
		name = "spidergland",
        label = "Spider Gland Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor5",
    },
	{
		name = "stinger",
        label = "Stinger Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor10",
    },
	{
		name = "tentaclespots",
        label = "Tentacle Spots Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "5Gfor1",
    },
	{
		name = "thulecite",
        label = "Thulecite Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "10Gfor1",
    },
	{
		name = "turf_road",
        label = "Cobblestones Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "3Gfor1",
    },
	{
		name = "turf_rocky",
        label = "Rocky Turf Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor1",
    },
	{
		name = "turf_forest",
        label = "Forest Turf Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor1",
    },
	{
		name = "turf_forest",
        label = "Forest Turf Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor1",
    },
	{
		name = "turf_marsh",
        label = "Marsh Turf Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor1",
    },
	{
		name = "turf_dirt",
        label = " Dirt Turf Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor1",
    },
	{
		name = "turf_forest",
        label = "Forest Turf Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor1",
    },
	{
		name = "turf_checkerfloor",
        label = "Checkered Turf Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "2Gfor1",
    },
	{
		name = "twigs",
        label = "Twigs Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor20",
    },
	{
		name = "walrus_tusk",
        label = "Walrus Tusk Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "30Gfor1",
    },
	{
		name = "yellowgem",
        label = "Yellow Gem Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "50Gfor1",
    },
	{
		name = "ash",
        label = "Ash Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor20",
    },
	{
		name = "beefalowool",
        label = "Beefalo Wool Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor2",
    },
	{
		name = "dug_sapling",
        label = "Sapling Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor1",
    },
	{
		name = "dug_berrybush",
        label = "Berrybush Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor1",
    },
	{
		name = "dug_berrybush2",
        label = "Berrybush2 Trading",
        options = 
        {	
			{description = "Don't Trade", data = "noTrade"},
			{description = "1 Gold for 40", data = "1Gfor40"}, 
			{description = "1 Gold for 20", data = "1Gfor20"}, 
			{description = "1 Gold for 10", data = "1Gfor10"}, 
		    {description = "1 Gold for 5", data = "1Gfor5"}, 
            {description = "1 Gold for 2", data = "1Gfor2"}, 
			{description = "1 Gold for 1", data = "1Gfor1"}, 
			{description = "2 Gold for 1", data = "2Gfor1"}, 
			{description = "3 Gold for 1", data = "3Gfor1"}, 
			{description = "5 Gold for 1", data = "5Gfor1"}, 
			{description = "10 Gold for 1", data = "10Gfor1"},
			{description = "20 Gold for 1", data = "20Gfor1"},	
			{description = "30 Gold for 1", data = "30Gfor1"},
			{description = "50 Gold for 1", data = "50Gfor1"},
			{description = "100 Gold for 1", data = "100Gfor1"},
			{description = "200 Gold for 1", data = "200Gfor1"},
			{description = "Don't Trade", data = "noTrade"},
        }, 
        default = "1Gfor1",
    },
}
