MARKETITEMLIST = {
--page1]
"cutgrass","rocks","log","flint","twigs","cutreeds","marble",
"dug_grass","dug_sapling","pinecone","dug_berrybush","dug_berrybush2","emptySpace","emptySpace",
"emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace",
"emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace",
"emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace",
"emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace",
"emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace",
"emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace",
--page2
--"emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace",
--"emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace",
--"emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace",
--"emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace",
--"emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace",
--"emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace",
--"emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace",
--"emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace","emptySpace",
}